[tool.black]
line-length = 79
target-version = ["py310"]

[tool.isort]
profile = "black"
filter_files = "True"
line_length = 79
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.ruff]
ignore = ["C901", "F403", "F405"]
line-length = 120
target-version= "py310"
